'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8944
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Reflection
Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class t

    Sub New()

    End Sub

    Sub New(name As String, type As String, ref As String)
        nameField = name
        typeField = type
        refField = ref

    End Sub

    Private refField As String

    Private typeField As String

    Private nameField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ref() As String
        Get
            Return Me.refField
        End Get
        Set
            Me.refField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    Public ReadOnly Property id As String
        Get
            Return Split(Split(refField, "\").Last, ".")(0)
        End Get
    End Property

    Public Shadows ReadOnly Property [GetType] As Object
        Get
            Return Assembly.GetExecutingAssembly.GetType(typeField)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class p

#Region "ctor"

    Sub New()

    End Sub

    Sub New(name As String, type As String, value As String)
        nameField = name
        typeField = type
        valueField = value

    End Sub

#End Region

    Private nameField As String

    Private typeField As String

    Private valueField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = Value
        End Set
    End Property
End Class

' System.Diagnostics.DebuggerStepThroughAttribute(),
'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class this

    Private pField As New List(Of p)

    Private tField As New List(Of t)

    Private aField As New List(Of thisA)

    Private typeField As String

    Private nameField As String

    Private idField As String

    Sub New()

    End Sub

    Sub New(ByRef fromThing As thing)
        With Me
            .id = fromThing.id
            .name = fromThing.Name
            .type = fromThing.GetType.ToString

            For Each PropertyInf As PropertyInfo In fromThing.GetType.GetProperties
                If PropertyInf.CanWrite Then
                    Select Case PropertyInf.Name.ToLower
                        Case "path", "name", "id", "ref", "loaded"

                        Case Else
                            If myThings.IsThing(PropertyInf.PropertyType) Then
                                If Not PropertyInf.GetValue(fromThing) Is Nothing Then
                                    .t.Add(
                                    New Speak.t(
                                        PropertyInf.Name,
                                        PropertyInf.GetValue(fromThing).GetType.ToString,
                                        PropertyInf.GetValue(fromThing).Ref
                                    )
                                )

                                End If

                            ElseIf Not IsNothing(TryCast(PropertyInf.GetValue(fromThing), things)) Then
                                With .a
                                    .Add(New thisA(PropertyInf.Name))
                                    With .Last.t
                                        For Each t As thing In TryCast(PropertyInf.GetValue(fromThing), things)
                                            .Add(
                                                New t(
                                                    t.Name,
                                                    t.GetType.ToString,
                                                    t.Ref
                                                )
                                            )

                                        Next
                                    End With

                                End With

                            Else
                                If Not PropertyInf.GetValue(fromThing) Is Nothing Then
                                    .p.Add(
                                    New Speak.p(
                                        PropertyInf.Name,
                                        PropertyInf.GetValue(fromThing).GetType.ToString,
                                        PropertyInf.GetValue(fromThing).ToString
                                    )
                                )
                                End If
                            End If

                    End Select

                End If
            Next

        End With
    End Sub

    Public Shadows ReadOnly Property [GetType] As Object
        Get
            Return Assembly.GetExecutingAssembly.GetType(typeField)
        End Get
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("p")>
    Public Property p As List(Of p)
        Get
            Return Me.pField
        End Get
        Set
            Me.pField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("t")>
    Public Property t As List(Of t)
        Get
            Return Me.tField
        End Get
        Set
            Me.tField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("a")>
    Public Property a As List(Of thisA)
        Get
            Return Me.aField
        End Get
        Set
            Me.aField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class thisA

    Private tField As New List(Of t)

    Private nameField As String

    Public Sub New()

    End Sub

    Public Sub New(name As String)
        nameField = name
    End Sub

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("t")>
    Public Property t As List(Of t)
        Get
            Return Me.tField
        End Get
        Set
            Me.tField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

End Class
